#!/bin/bash

# Backup the original /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Add custom entries to the /etc/hosts file
sudo bash -c 'echo "127.0.0.2 localhost" >> /etc/hosts'
sudo bash -c 'sed -i "s/^[0-9]*\.[0-9]*\.[0-9]*\.[0-9]* facebook.com/facebook.com/g" /etc/hosts'
sudo bash -c 'echo "8.8.8.8 facebook.com" >> /etc/hosts'

echo "Changes have been made. Please check with 'ping localhost' and 'ping facebook.com'."
